name: BamBam
main: PixelGuy75\BamBam\Main
version: 1.0
api: 1.10.0
author: PixelGuy75
commands:
 bang:
  description: Starts a RussianRoulette game!
  usage: /bam
  permission: bambam.command.bam
  aliases: [b]
permissions:
 bambam:
  default: false
  description: Allows access of all BamBam features
  children:
   bambam.command:
    default: false
    description: Allows usage of all BamBam commands
    children:
     bambam.command.bam:
      default: true
      description: Allows usage of /bam
